---
title: "Patterns of Physical Activity Among Adolescents"
author: "Team Bates, Castro, and Farley"
date: "11/27/2021"
output: 
  html_document:
        toc: true
        toc_float: true
        toc_depth: 3
        highlight: pygments
        code_folding: hide
        bibliography: references.bib
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      fig.width = 9, 
                      fig.height = 9)

#load packages
```

# Abstract

# Introduction

(define significance of our topic) Adolescent physical activity is important to ***
This project used data from the Family Life, Activity, Sun, Health and Eating (FLASHE) study to examine patterns of adolescent physical activity, including when they exercise, how much they exercise, and to explore the association between adolescent BMI, sex, and school type with their exercise patterns. The FLASHE study was conducted by the National Cancer Institute in 2014. Through a cross-sectional, internet-based design, it collected responses from parents and teens to look at psychosocial, generational, and environmental correlates of cancer-related behaviors (CITE from https://cancercontrol.cancer.gov/brp/hbrb/flashe-study)  
* i want to try Havi's 'share' for how to include a website image in the paper and bring in the FLASHE Conceptual model here. 

## Research Questions (to be changed based on figures. included as placeholders)

**1. How do patterns of physical activity for adolescents (when they exercise) vary by their BMI and demographics(school type, sex and age)?**

**2. How does the total amount of exercise (or average exercise) relate to BMI and demographics?**

# Method 
#can insert inline code into each section below

## Joining Data Sets
Our data was split into 2 files for size/downloadable reasons so we
joined it to make one usable data file.  
We chose full join because we wanted all of the variables to appropriately merge the data sets.

## Cleaning data - {select},  {characterize}, and {filter} 
We then wanted to characterize only select variables, hence the use of the {select}--> {characterize} functions. We could not find a way to characterize the data set as a whole without turning some variables' values to NA, so we selected certain variables, characterized them, then rejoined the data sets with the newly characterized data.

Our analysis focuses on adolescents so we {filter}ed out participants age 13-18. 

## Calculating BMI - {mutate}
Body Mass Index (BMI) is an effective measure of _____(Esme and Zach this is your wheel house, so leaving this definition and noting importance of BMI to you :) 
To calculate BMI, we utilized the {mutate} function. 

## Calculating Mean Physical Activity - {summarize} and {group_by}
 The {group_by} function allowed us to organize our data by school type and sex to appropriately assess for associations between those demographic variables and average total weekly physical activity.
 
## {pivot_Longer} for organzing when physical activity occurs
The initial data set divided when physical activity was completed by during the week in school (XTPREDWEEKS), during the week out of school (XTPREDWEEKOFS), and on the weekend(XTPREDWEEKW). Using {pivot_longer}, we combined the variables of when/where the physical activity was completed to better visualize across the pattern of when/where and any associations with demographic variables. 

# Results
We found that ***
## Summary Table

have code for the summary table in script and can turn it into a plot like bar/col or error bars

## Figure 1
## Figure 2
## Figure 3

# Discussion

Based on our analysis of adolescents who participated in the FLASE study...
Implications for programs to promote physical activity in or out of school..
Implications for policy..
Next steps for research include examining what motivates adolescents to complete physical activity, and how their environment moderates or mediates the amount of physical activity they complete.

# References 
\newpage